using System;

namespace SoftwaredeveloperDotAt.Infrastructure.Core.Sections.DemoData
{
    public static class DemoDataHelper
    {
        public static string[] MaleFirstNames = [
              "Jacob",
            "Mason",
            "Ethan",
            "Logan",
            "Liam",
            "Noah",
            "William",
            "James",
            "Benjamin",
            "Alexander",
            "Michael",
            "Daniel",
            "Henry",
            "Andrew",
            "David",
            "Joseph",
            "Lucas",
            "Jackson",
            "Samuel",
            "Sebastian",
            "Jack",
            "Aiden",
            "Owen",
            "Dylan",
            "Luke",
            "Gabriel",
            "Carter",
            "Matthew",
            "Jayden",
            "Isaac",
            "Julian",
            "Levi",
            "Josiah",
            "Sawyer",
            "Ryan",
            "Nathan",
            "Hunter",
            "Christian",
            "Jaxon",
            "Lincoln",
            "Kayden",
            "Aaron",
            "Charles",
            "Brayden",
            "Diego",
            "Miguel",
            "Alejandro",
            "Caleb",
            "Ezra",
            "Kyle",
            "Colton",
            "Max",
            "Thomas",
            "Juan",
            "Connor",
            "Dominic",
            "Ian",
            "Gavin",
            "Jeremiah",
            "Elias",
            "Cooper",
            "Hudson",
            "Miles",
            "Adrian",
            "Leo",
            "Mateo",
            "Silas",
            "Austin",
            "Jordan",
            "Nicolas",
            "Jasper",
            "Adam",
            "Xavier",
            "Greyson",
            "Jose",
            "Ezekiel",
            "Carson",
            "Evan",
            "Maverick",
            "Bryson",
            "Jace",
            "Nathaniel",
            "Theo",
            "Luis",
            "Parker",
            "Cameron",
            "Micah",
            "Jason",
            "Ayden",
            "Chase",
            "Finley",
            "Ivan",
            "Josue",
            "Tristan",
            "Bentley",
            "Damian",
            "Caden",
            "Blake",
            "Elliot",
            "Keegan",
            "Lane",
            "Rylan",
            "Paxton",
            "Maximiliano",
            "Karson",
            "Jameson",
            "Kevin",
            "Zane",
            "Graham",
            "Weston",
            "Antonio",
            "Brooks",
            "Simon",
            "Asher",
            "Matteo",
            "Oscar",
            "Felix",
            "Emil",
            "Hugo",
            "Oliver",
            "Theodore",
            "Rafael",
            "Victor",
            "Vincent",
            "Roman",
            "Francisco",
            "Alberto",
            "Eduardo",
            "Rodrigo",
            "Sergio",
            "Igor",
            "Yuri",
            "Luca",
            "Stefan",
            "Nikolai",
            "Andrei",
            "Luka",
            "Marco",
            "Ricardo",
            "Alexei",
            "Mikhail",
            "Ivan",
            "Vladimir",
            "Artem",
            "Dmitri",
            "Oleg",
            "Ruslan",
            "Viktor",
            "Yaroslav",
            "Anatoly",
            "Boris",
            "Konstantin",
            "Leonid",
            "Maksim",
            "Pavel",
            "Roman",
            "Sergei",
            "Vladislav",
            "Yegor",
            "Artyom",
            "Ilya",
            "Kirill",
            "Miroslav",
            "Nikita",
            "Pyotr",
            "Stanislav",
            "Vasili",
            "Alexandr",
            "Dmitry",
            "Evgeny",
            "Fyodor",
            "Grigory",
            "Ivan",
            "Leon",
            "Mikhail",
            "Nikolay",
            "Oleg",
            "Pavel",
            "Ruslan",
            "Sergey",
            "Vladimir",
            "Yuri",
            "Anatoliy",
            "Bogdan",
            "Vadim",
            "Yaroslav",
            "Artemiy",
            "Igor",
            "Konstantin",
            "Maxim",
            "Nikolai",
            "Oleg",
            "Petr",
            "Roman",
            "Semyon",
            "Timofey",
            "Vasily",
            "Yevgeny",
            "Aleksandr",
            "Dmitrii",
            "Egor",
            "Fedor",
            "Georgiy",
            "Ilya",
            "Klim",
            "Lev",
            "Maksim",
            "Nikita",
            "Oskar",
            "Pavel",
            "Rodion",
            "Saveliy",
            "Stepan",
            "Tikhon",
            "Viktor",
            "Yakov",
            "Zakhar"
        ];

        public static string[] FemaleFirstNames = [
              "Emma",
            "Sophia",
            "Olivia",
            "Isabella",
            "Ava",
            "Mia",
            "Zoe",
            "Lily",
            "Amelia",
            "Harper",
            "Madison",
            "Ella",
            "Charlotte",
            "Avery",
            "Sofia",
            "Chloe",
            "Layla",
            "Riley",
            "Anna",
            "Bella",
            "Grace",
            "Natalie",
            "Luna",
            "Victoria",
            "Eleanor",
            "Nora",
            "Scarlett",
            "Maya",
            "Elizabeth",
            "Penelope",
            "Ariana",
            "Eliana",
            "Ivy",
            "Sadie",
            "Piper",
            "Ruby",
            "Serenity",
            "Willow",
            "Quinn",
            "Alice",
            "Cora",
            "Julia",
            "Clara",
            "Vivian",
            "Reagan",
            "Camila",
            "Gianna",
            "Rae",
            "Eliza",
            "Lila",
            "Elise",
            "Juliet",
            "Sienna",
            "Fiona",
            "Valentina",
            "Isabel",
            "Kennedy",
            "Gabriella",
            "Lydia",
            "Daniela",
            "Jade",
            "Peyton",
            "Maria",
            "Naomi",
            "Alina",
            "Adeline",
            "Ariana",
            "Eva",
            "Harley",
            "Brianna",
            "Rose",
            "Mackenzie",
            "Stella",
            "Lilly",
            "Aubrey",
            "Kylie",
            "Ashley",
            "Jasmine",
            "Alexis",
            "Alice",
            "Kaylee",
            "Isabella",
            "Sophie",
            "Charlotte",
            "Amara",
            "Valerie",
            "Kaitlyn",
            "Harper",
            "Savannah",
            "Annabelle",
            "Faith",
            "Zoey",
            "Elena",
            "Lola",
            "Angela",
            "Natalia",
            "Lucia",
            "Adalynn",
            "Julianna",
            "Leah",
            "Aurora",
            "Marley",
            "Juliette",
            "Amelia",
            "Katherine",
            "Mariah",
            "Aaliyah",
            "Samantha",
            "Lana",
            "Violet",
            "Elsie",
            "Elena",
            "Gabrielle",
            "Melanie",
            "Sierra",
            "Violeta",
            "Liliana",
            "Helena",
            "Irina",
            "Yulia",
            "Svetlana",
            "Nataliya",
            "Anastasia",
            "Ekaterina",
            "Ksenia",
            "Olga",
            "Tatiana",
            "Ludmila",
            "Maria",
            "Nadezhda",
            "Oksana",
            "Polina",
            "Sofiya",
            "Vera",
            "Darya",
            "Elena",
            "Galina",
            "Irina",
            "Klara",
            "Larisa",
            "Margarita",
            "Nina",
            "Raisa",
            "Svetlana",
            "Tatyana",
            "Valentina",
            "Yana",
            "Zhanna",
            "Alina",
            "Anya",
            "Bella",
            "Vika",
            "Dina",
            "Eva",
            "Galya",
            "Inna",
            "Kira",
            "Lena",
            "Masha",
            "Nastya",
            "Olya",
            "Pasha",
            "Rita",
            "Sasha",
            "Tanya",
            "Ulya",
            "Valya",
            "Zoya",
            "Alya",
            "Dasha",
            "Elina",
            "Faina",
            "Grusha",
            "Hanna",
            "Ira",
            "Jenya",
            "Katya",
            "Liza",
            "Mila",
            "Nadia",
            "Olesya",
            "Petya",
            "Rima",
            "Stasya",
            "Tasha",
            "Varya",
            "Yulia",
            "Zina",
            "Alisa",
            "Anfisa",
            "Daria",
            "Elizaveta",
            "Faina",
            "Greta",
            "Helen",
            "Ivanna",
            "Jana",
            "Karina",
            "Lana",
            "Mira",
            "Nona",
            "Oxana",
            "Polina",
            "Rina",
            "Sonya",
            "Taisiya",
            "Uliana",
            "Valeria",
            "Yaroslava",
            "Zlata"
        ];

        public static string[] FirstNames = MaleFirstNames.Concat(FemaleFirstNames).ToArray();

        public static string[] LastNames = [
            "Müller",
            "Schmidt",
            "Schneider",
            "Fischer",
            "Weber",
            "Meyer",
            "Wagner",
            "Becker",
            "Schulz",
            "Hoffmann",
            "Schäfer",
            "Koch",
            "Bauer",
            "Richter",
            "Klein",
            "Wolf",
            "Schröder",
            "Neumann",
            "Schwarz",
            "Zimmermann",
            "Braun",
            "Krüger",
            "Hofmann",
            "Hartmann",
            "Lange",
            "Schmitt",
            "Werner",
            "Schmitz",
            "Krause",
            "Meier",
            "Lehmann",
            "Schmid",
            "Schulze",
            "Maier",
            "Köhler",
            "Herrmann",
            "Walter",
            "König",
            "Mayer",
            "Huber",
            "Kaiser",
            "Fuchs",
            "Peters",
            "Lang",
            "Scholz",
            "Möller",
            "Weiß",
            "Jung",
            "Hahn",
            "Schubert",
            "Vogel",
            "Friedrich",
            "Keller",
            "Günther",
            "Frank",
            "Berger",
            "Winkler",
            "Roth",
            "Beck",
            "Lorenz",
            "Baumann",
            "Franke",
            "Albrecht",
            "Schuster",
            "Simon",
            "Ludwig",
            "Böhm",
            "Winter",
            "Kraus",
            "Martin",
            "Schumacher",
            "Krämer",
            "Vogt",
            "Stein",
            "Jäger",
            "Otto",
            "Sommer",
            "Groß",
            "Seidel",
            "Heinrich",
            "Brandt",
            "Haas",
            "Schreiber",
            "Graf",
            "Schulte",
            "Dietrich",
            "Ziegler",
            "Kuhn",
            "Pohl",
            "Engel",
            "Horn",
            "Busch",
            "Bergmann",
            "Thomas",
            "Voigt",
            "Sauer",
            "Arnold",
            "Wolff",
            "Pfeiffer",
            "Schultze",
            "Wiese",
            "Reuter",
            "Bohn",
            "Voß",
            "Schenk",
            "Döring",
            "Schütz",
            "Behrens",
            "Moser",
            "Schiller",
            "Götz",
            "Paul",
            "Unger",
            "Dietz",
            "Breuer",
            "Ackermann",
            "May",
            "Herzog",
            "Seifert",
            "Hesse",
            "Schröter",
            "Hahn",
            "Friedl",
            "Geiger",
            "Bachmann",
            "Jacob",
            "Reinhardt",
            "Maurer",
            "Wilhelm",
            "Hermann",
            "Diehl",
            "Hartung",
            "Heller",
            "Hinz",
            "Ebert",
            "Arndt",
            "Franz",
            "Thiele",
            "Fink",
            "Kruse",
            "Schrödter",
            "Michel",
            "Krauß",
            "Eckert",
            "Dietrich",
            "Hesse",
            "Burkhardt",
            "Böttcher",
            "Wiedemann",
            "Köhler",
            "Lechner",
            "Rausch",
            "Eckert",
            "Graf",
            "Schreiner",
            "Küster",
            "Krämer",
            "Urban",
            "Mair",
            "Schmitz",
            "Stark",
            "Bach",
            "Hartl",
            "Schwarze",
            "Böttcher",
            "Blum",
            "Hofmann",
            "Sander",
            "Hoch",
            "Stahl",
            "Ullrich",
            "Unger",
            "Moser",
            "Schulte",
            "Haber",
            "Schott",
            "Hagedorn",
            "Klemm",
            "Mayr",
            "Kern",
            "Kretschmer",
            "May",
            "Pilz",
            "Merkel",
            "Kirchner",
            "Stadler",
            "Reimann",
            "Fleischmann",
            "Hein",
            "Hemmer",
            "Jahn",
            "Kellner",
            "Schick",
            "Hertel",
            "Krupp",
            "Gebhardt",
            "Schnell",
            "Kleiner",
            "Zeller",
            "Schott",
            "Hauser",
            "Riedel",
            "Berg",
            "Luther",
            "Reich",
            "Held",
            "Mack",
            "Hennig",
            "Weidner",
            "Hirsch",
            "Kolb",
            "Löhr",
            "Wüst",
            "Strauß",
            "Scholz",
            "Heinz",
            "Riedl",
            "Dörr",
            "Höfer",
            "Schweitzer",
            "Heinzel",
            "Behr",
            "Ludwig",
            "Wulf",
            "Siegert",
            "Bosch",
            "Schöne",
            "Dorn",
            "Bartels",
            "Höhne",
            "Schüler",
            "Petersen",
            "Ritter",
            "Schuler",
            "Krug",
            "Falk",
            "Niemann",
            "Freitag",
            "Rösch",
            "Schröter",
            "Lenz",
            "Bachmann",
            "Seemann",
            "Reinhold",
            "Schlegel",
            "Herr",
            "Meister",
            "Werner",
            "Rupp",
            "Kolbe",
            "Hildebrand",
            "Schön",
            "Häuser",
            "Roth",
            "Fiedler",
            "Hilbert",
            "Sturm",
            "Wirtz",
            "Sattler",
            "Schwarzer",
            "Büchner",
            "Röder",
            "Heinrich",
            "Mielke",
            "Schweizer",
            "Hoppe",
            "Keller",
            "Wunderlich",
            "Wulff",
            "Küppers",
            "Junge",
            "Scholze",
            "Bauer",
            "Frick",
            "Freund",
            "Kappler",
            "Schönfeld",
            "Heise",
            "Hohmann",
            "Seitz",
            "Brand",
            "Junker",
            "Heinemann",
            "Schleicher",
            "Lohmann",
            "Weiland",
            "Hornung",
            "Böhme",
            "Hummel",
            "Böhm",
            "Marx",
            "Wolter",
            "Schneider",
            "Kaplan",
            "Kahl",
            "Münch",
            "Schultheis",
            "Timm",
            "Wittmann",
            "Schober"];

        public static Adresse[] Adressen =
        [
            // Österreich
            new Adresse { City = "Wien", ZipCode = "1010", Street = "Mariahilfer Straße", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Graz", ZipCode = "8010", Street = "Herrengasse", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Linz", ZipCode = "4020", Street = "Landstraße", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1010", Street = "Stephansplatz 1", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1050", Street = "Reinprechtsdorfer Straße 42", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1020", Street = "Praterstraße 44", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1030", Street = "Landstraßer Hauptstraße 27", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1040", Street = "Wiedner Hauptstraße 36", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1050", Street = "Margaretenstraße 72", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1060", Street = "Mariahilfer Straße 88", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1070", Street = "Neubaugasse 15", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1080", Street = "Josefstädter Straße 21", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1090", Street = "Alser Straße 39", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1100", Street = "Favoritenstraße 118", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1110", Street = "Simmeringer Hauptstraße 96", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1120", Street = "Meidlinger Hauptstraße 63", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1130", Street = "Hietzinger Hauptstraße 22", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1140", Street = "Linzer Straße 142", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1150", Street = "Mariahilfer Straße 182", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1160", Street = "Thaliastraße 88", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1170", Street = "Hernalser Hauptstraße 45", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1180", Street = "Währinger Straße 19", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1190", Street = "Heiligenstädter Straße 31", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1200", Street = "Brigittenauer Lände 72", Country = "Österreich", ISO3 = "AUT" },

            new Adresse { City = "Graz", ZipCode = "8010", Street = "Herrengasse 10", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Graz", ZipCode = "8020", Street = "Lendplatz 35", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Linz", ZipCode = "4020", Street = "Landstraße 12", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Linz", ZipCode = "4040", Street = "Hauptstraße 23", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Salzburg", ZipCode = "5020", Street = "Getreidegasse 47", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Salzburg", ZipCode = "5061", Street = "Elisabethstraße 6", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Innsbruck", ZipCode = "6020", Street = "Maria-Theresien-Straße 15", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Innsbruck", ZipCode = "6080", Street = "Innrain 52", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Klagenfurt", ZipCode = "9020", Street = "Bahnhofstraße 8", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Klagenfurt", ZipCode = "9073", Street = "Viktringer Ring 26", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Villach", ZipCode = "9500", Street = "Hauptplatz 19", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Villach", ZipCode = "9524", Street = "St. Magdalener Straße 7", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wels", ZipCode = "4600", Street = "Stadtplatz 34", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wels", ZipCode = "4614", Street = "Traunuferstraße 122", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "St. Pölten", ZipCode = "3100", Street = "Wiener Straße 58", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "St. Pölten", ZipCode = "3107", Street = "Kremser Landstraße 4", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Dornbirn", ZipCode = "6850", Street = "Marktplatz 11", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Dornbirn", ZipCode = "6850", Street = "Schulgasse 23", Country = "Österreich", ISO3 = "AUT" },
            new Adresse { City = "Wien", ZipCode = "1010", Street = "Kärntner Straße 51", Country = "Österreich", ISO3 = "AUT" },

            // Deutschland
            new Adresse { City = "Berlin", ZipCode = "10117", Street = "Pariser Platz", Country = "Deutschland", ISO3 = "DEU" },
            new Adresse { City = "München", ZipCode = "80337", Street = "Sendlinger Straße", Country = "Deutschland", ISO3 = "DEU" },
            new Adresse { City = "Hamburg", ZipCode = "20457", Street = "Speicherstadt", Country = "Deutschland", ISO3 = "DEU" },
            // Frankreich
            new Adresse { City = "Paris", ZipCode = "75004", Street = "Rue de Rivoli", Country = "Frankreich", ISO3 = "FRA" },
            new Adresse { City = "Lyon", ZipCode = "69002", Street = "Rue du Bât d'Argent", Country = "Frankreich", ISO3 = "FRA" },
            new Adresse { City = "Marseille", ZipCode = "13002", Street = "La Canebière", Country = "Frankreich", ISO3 = "FRA" },
            // Spanien
            new Adresse { City = "Madrid", ZipCode = "28014", Street = "Paseo del Prado", Country = "Spanien", ISO3 = "ESP" },
            new Adresse { City = "Barcelona", ZipCode = "08002", Street = "La Rambla", Country = "Spanien", ISO3 = "ESP" },
            new Adresse { City = "Sevilla", ZipCode = "41004", Street = "Calle Sierpes", Country = "Spanien", ISO3 = "ESP" },
            // Italien
            new Adresse { City = "Rom", ZipCode = "00186", Street = "Via del Corso", Country = "Italien", ISO3 = "ITA" },
            new Adresse { City = "Mailand", ZipCode = "20121", Street = "Via Dante", Country = "Italien", ISO3 = "ITA" },
            new Adresse { City = "Venedig", ZipCode = "30124", Street = "Piazza San Marco", Country = "Italien", ISO3 = "ITA" },
            // Belgien
            new Adresse { City = "Brüssel", ZipCode = "1000", Street = "Rue Royale", Country = "Belgien", ISO3 = "BEL" },
            new Adresse { City = "Antwerpen", ZipCode = "2000", Street = "Meir", Country = "Belgien", ISO3 = "BEL" },
            new Adresse { City = "Gent", ZipCode = "9000", Street = "Graslei", Country = "Belgien", ISO3 = "BEL" },
            // Niederlande
            new Adresse { City = "Amsterdam", ZipCode = "1012", Street = "Damrak", Country = "Niederlande", ISO3 = "NLD" },
            new Adresse { City = "Rotterdam", ZipCode = "3011", Street = "Coolsingel", Country = "Niederlande", ISO3 = "NLD" },
            new Adresse { City = "Den Haag", ZipCode = "2511", Street = "Lange Voorhout", Country = "Niederlande", ISO3 = "NLD" },
            // Polen
            new Adresse { City = "Warschau", ZipCode = "00-001", Street = "Aleje Jerozolimskie", Country = "Polen", ISO3 = "POL" },
            new Adresse { City = "Krakau", ZipCode = "31-011", Street = "Rynek Główny", Country = "Polen", ISO3 = "POL" },
            new Adresse { City = "Gdańsk", ZipCode = "80-001", Street = "Długa", Country = "Polen", ISO3 = "POL" },
            // Griechenland
            new Adresse { City = "Athen", ZipCode = "105 57", Street = "Ermou", Country = "Griechenland", ISO3 = "GRC" },
            new Adresse { City = "Thessaloniki", ZipCode = "546 21", Street = "Tsimiski", Country = "Griechenland", ISO3 = "GRC" },
            new Adresse { City = "Patras", ZipCode = "262 21", Street = "Maizonos", Country = "Griechenland", ISO3 = "GRC" },
            // Schweden
            new Adresse { City = "Stockholm", ZipCode = "111 29", Street = "Västerlånggatan", Country = "Schweden", ISO3 = "SWE" },
            new Adresse { City = "Göteborg", ZipCode = "411 06", Street = "Kungsgatan", Country = "Schweden", ISO3 = "SWE" },
            new Adresse { City = "Malmö", ZipCode = "211 39", Street = "Södergatan", Country = "Schweden", ISO3 = "SWE" },
            // Ungarn
            new Adresse { City = "Budapest", ZipCode = "1051", Street = "Váci utca", Country = "Ungarn", ISO3 = "HUN" },
            new Adresse { City = "Debrecen", ZipCode = "4024", Street = "Piac utca", Country = "Ungarn", ISO3 = "HUN" },
            new Adresse { City = "Szeged", ZipCode = "6720", Street = "Kárász utca", Country = "Ungarn", ISO3 = "HUN" },
            // Tschechische Republik
            new Adresse { City = "Prag", ZipCode = "110 00", Street = "Wenzelsplatz", Country = "Tschechische Republik", ISO3 = "CZE" },
            new Adresse { City = "Brünn", ZipCode = "602 00", Street = "Masarykova", Country = "Tschechische Republik", ISO3 = "CZE" },
            new Adresse { City = "Ostrava", ZipCode = "702 00", Street = "Stodolní", Country = "Tschechische Republik", ISO3 = "CZE" },
            // Portugal
            new Adresse { City = "Lissabon", ZipCode = "1100-388", Street = "Rua Augusta", Country = "Portugal", ISO3 = "PRT" },
            new Adresse { City = "Porto", ZipCode = "4000-123", Street = "Rua de Santa Catarina", Country = "Portugal", ISO3 = "PRT" },
            new Adresse { City = "Braga", ZipCode = "4700-320", Street = "Avenida da Liberdade", Country = "Portugal", ISO3 = "PRT" },
            // Finnland
            new Adresse { City = "Helsinki", ZipCode = "00100", Street = "Mannerheimintie", Country = "Finnland", ISO3 = "FIN" },
            new Adresse { City = "Espoo", ZipCode = "02100", Street = "Tapiolantie", Country = "Finnland", ISO3 = "FIN" },
            new Adresse { City = "Tampere", ZipCode = "33100", Street = "Hämeenkatu", Country = "Finnland", ISO3 = "FIN" },
            // Lettland
            new Adresse { City = "Riga", ZipCode = "LV-1010", Street = "Brīvības iela", Country = "Lettland", ISO3 = "LVA" },
            new Adresse { City = "Daugavpils", ZipCode = "LV-5401", Street = "Vienības iela", Country = "Lettland", ISO3 = "LVA" },
            // Litauen
            new Adresse { City = "Vilnius", ZipCode = "LT-01100", Street = "Gedimino prospektas", Country = "Litauen", ISO3 = "LTU" },
            new Adresse { City = "Kaunas", ZipCode = "LT-44280", Street = "Laisvės alėja", Country = "Litauen", ISO3 = "LTU" },
            // Estland
            new Adresse { City = "Tallinn", ZipCode = "10111", Street = "Pikk tänav", Country = "Estland", ISO3 = "EST" },
            new Adresse { City = "Tartu", ZipCode = "51003", Street = "Riia tänav", Country = "Estland", ISO3 = "EST" },
            new Adresse { City = "Tallinn", ZipCode = "10111", Street = "Viru", Country = "Estland", ISO3 = "EST" },
            // Slowakei
            new Adresse { City = "Bratislava", ZipCode = "811 06", Street = "Obchodná ulica", Country = "Slowakei", ISO3 = "SVK" },
            new Adresse { City = "Košice", ZipCode = "040 01", Street = "Hlavná ulica", Country = "Slowakei", ISO3 = "SVK" },
            // Slowenien
            new Adresse { City = "Ljubljana", ZipCode = "1000", Street = "Prešernov trg", Country = "Slowenien", ISO3 = "SVN" },
            new Adresse { City = "Maribor", ZipCode = "2000", Street = "Gosposka ulica", Country = "Slowenien", ISO3 = "SVN" },
            // Kroatien
            new Adresse { City = "Zagreb", ZipCode = "10000", Street = "Ilica", Country = "Kroatien", ISO3 = "HRV" },
            new Adresse { City = "Split", ZipCode = "21000", Street = "Riva", Country = "Kroatien", ISO3 = "HRV" },
            // Bulgarien
            new Adresse { City = "Sofia", ZipCode = "1000", Street = "Vitosha Boulevard", Country = "Bulgarien", ISO3 = "BGR" },
            new Adresse { City = "Plovdiv", ZipCode = "4000", Street = "Glavnata", Country = "Bulgarien", ISO3 = "BGR" },
            new Adresse { City = "Sofia", ZipCode = "1000", Street = "Vitosha Boulevard", Country = "Bulgarien", ISO3 = "BGR" },
            // Rumänien
            new Adresse { City = "Bukarest", ZipCode = "010011", Street = "Calea Victoriei", Country = "Rumänien", ISO3 = "ROU" },
            new Adresse { City = "Cluj-Napoca", ZipCode = "400000", Street = "Bulevardul Eroilor", Country = "Rumänien", ISO3 = "ROU" },
            // Dänemark
            new Adresse { City = "Kopenhagen", ZipCode = "1000", Street = "Strøget", Country = "Dänemark", ISO3 = "DNK" },
            new Adresse { City = "Aarhus", ZipCode = "8000", Street = "Ryesgade", Country = "Dänemark", ISO3 = "DNK" },
            new Adresse { City = "Odense", ZipCode = "5000", Street = "Kongensgade", Country = "Dänemark", ISO3 = "DNK" },

            // Slowakei
            new Adresse { City = "Bratislava", ZipCode = "811 06", Street = "Obchodná", Country = "Slowakei", ISO3 = "SVK" },
            new Adresse { City = "Košice", ZipCode = "040 01", Street = "Hlavná", Country = "Slowakei", ISO3 = "SVK" },
            new Adresse { City = "Prešov", ZipCode = "080 01", Street = "Hlavná", Country = "Slowakei", ISO3 = "SVK" },

            // Irland
            new Adresse { City = "Dublin", ZipCode = "D02", Street = "Grafton Street", Country = "Irland", ISO3 = "IRL" },
            new Adresse { City = "Cork", ZipCode = "T12", Street = "Patrick's Street", Country = "Irland", ISO3 = "IRL" },
            new Adresse { City = "Galway", ZipCode = "H91", Street = "Shop Street", Country = "Irland", ISO3 = "IRL" },

            // Litauen
            new Adresse { City = "Vilnius", ZipCode = "01100", Street = "Gedimino prospektas", Country = "Litauen", ISO3 = "LTU" },
            new Adresse { City = "Kaunas", ZipCode = "44200", Street = "Laisvės alėja", Country = "Litauen", ISO3 = "LTU" },
            new Adresse { City = "Klaipėda", ZipCode = "92100", Street = "Taikos prospektas", Country = "Litauen", ISO3 = "LTU" },

            // Lettland
            new Adresse { City = "Riga", ZipCode = "LV-1050", Street = "Brīvības iela", Country = "Lettland", ISO3 = "LVA" },
            new Adresse { City = "Daugavpils", ZipCode = "LV-5401", Street = "Rīgas iela", Country = "Lettland", ISO3 = "LVA" },
            new Adresse { City = "Liepāja", ZipCode = "LV-3401", Street = "Kūrmājas prospekts", Country = "Lettland", ISO3 = "LVA" },

            // Kroatien
            new Adresse { City = "Zagreb", ZipCode = "10000", Street = "Ilica", Country = "Kroatien", ISO3 = "HRV" },
            new Adresse { City = "Split", ZipCode = "21000", Street = "Riva", Country = "Kroatien", ISO3 = "HRV" },
            new Adresse { City = "Rijeka", ZipCode = "51000", Street = "Korzo", Country = "Kroatien", ISO3 = "HRV" },

            // Slowenien
            new Adresse { City = "Ljubljana", ZipCode = "1000", Street = "Slovenska cesta", Country = "Slowenien", ISO3 = "SVN" },
            new Adresse { City = "Maribor", ZipCode = "2000", Street = "Ulica Kneza Koclja", Country = "Slowenien", ISO3 = "SVN" },
            new Adresse { City = "Koper", ZipCode = "6000", Street = "Pristaniška ulica", Country = "Slowenien", ISO3 = "SVN" },

            // Zypern
            new Adresse { City = "Nikosia", ZipCode = "1010", Street = "Ledra", Country = "Zypern", ISO3 = "CYP" },
            new Adresse { City = "Limassol", ZipCode = "3105", Street = "Anexartisias", Country = "Zypern", ISO3 = "CYP" },
            new Adresse { City = "Paphos", ZipCode = "8046", Street = "Poseidonos", Country = "Zypern", ISO3 = "CYP" },
        ];

    }
}

