namespace SoftwaredeveloperDotAt.Infrastructure.Core.Sections.DemoData
{
    public static class DemoDataHelper
    {
        public static string[] FirstNames = ["John", "Jane", "Michael", "Jessica", "David", "Ashley", "Chris", "Amanda", "James", "Sarah", "Robert", "Jennifer", "Daniel", "Emily", "Matthew", "Samantha", "Joseph", "Brittany", "Andrew", "Stephanie", "Ryan", "Nicole", "Brandon", "Elizabeth", "Tyler", "Megan", "Nicholas", "Kayla", "Adam", "Amber", "Zachary", "Rachel", "Justin", "Lauren", "Kevin", "Courtney", "Eric", "Danielle", "Steven", "Heather", "Thomas", "Melissa", "Timothy", "Rebecca", "Kyle", "Michelle", "Jeffrey", "Tiffany", "Brian", "Chelsea", "Cody", "Christina", "Richard", "Katherine", "Jeremy", "Alyssa", "Aaron", "Jenna", "Mark", "Marissa", "Charles", "Laura", "Stephen", "Hannah", "Patrick", "Kimberly", "Scott", "Victoria", "Paul", "Alexandra", "Derek", "Kelly", "Sean", "Sara", "Keith", "Erin", "Benjamin", "Lisa", "Gregory", "Andrea", "Jesse", "Kristen", "Cory", "Kristin", "Chad", "Lindsey", "Shawn", "Katie", "Travis", "Allison", "Bryan", "Cassandra", "Juan", "Catherine", "Jared", "Monica", "Erik", "April", "Jordan", "Kathryn", "Samuel", "Natalie", "Cameron", "Leah", "Christian", "Alexis", "Victor", "Kristina", "Philip", "Veronica", "Adrian", "Margaret", "Dylan", "Anna", "Dustin", "Caitlin", "Donald", "Brandy", "Frank", "Tara", "Brett", "Julia", "Lucas", "Molly", "Peter", "Erika", "George", "Jillian", "Antonio", "Kara", "Alejandro", "Oliver", "Jack", "Harry", "Jacob", "Charlie", "Thomas", "George", "Oscar", "James", "William", "Alfie", "Joshua", "Henry", "Leo", "Archie", "Ethan", "Joseph", "Freddie", "Samuel", "Alexander", "Logan", "Daniel", "Isaac", "Max", "Mohammed", "Benjamin", "Mason", "Lucas", "Edward", "Harrison", "Jake", "Dylan", "Riley", "Finley", "Theo", "Sebastian", "Adam", "Zachary", "Arthur", "Toby", "Jayden", "Luke", "Harvey", "Lewis", "Tyler", "Matthew", "David", "Reuben", "Michael", "Luca", "Teddy", "Stanley", "Tommy", "Jenson", "Bobby", "Caleb", "Elliot", "Albert", "Elliott", "Reggie", "Frankie", "Jude", "Louis", "Ronnie", "Tom", "Rory", "Harley", "Jasper", "Ollie", "Carter", "Elijah", "Finn", "Jaxson", "Kai", "Liam", "Nathan", "Parker", "Alex", "Blake", "Cody", "Dexter", "Ellis", "Kian", "Milo", "Rowan", "Seth", "Sonny", "Taylor", "Zack", "Aidan", "Albie", "Arlo", "Asher", "Barnaby", "Brodie", "Cameron", "Casper", "Ezra", "Felix", "Fletcher", "Gabriel", "Hugo", "Ibrahim", "Jesse", "Kaiden", "Kian", "Kieran", "Lenny", "Leon", "Lyle", "Maddox", "Marley", "Myles", "Nico", "Nolan", "Orson", "Otis", "Rex", "Rocco", "Rudy", "Sawyer", "Sergio", "Tate", "Tobias", "Troy", "Yusuf", "Zain"];
        public static string[] LastNames = ["Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann", "Schäfer", "Koch", "Bauer", "Richter", "Klein", "Wolf", "Schröder", "Neumann", "Schwarz", "Zimmermann", "Braun", "Krüger", "Hofmann", "Hartmann", "Lange", "Schmitt", "Werner", "Schmitz", "Krause", "Meier", "Lehmann", "Schmid", "Schulze", "Maier", "Köhler", "Herrmann", "König", "Mayer", "Walter", "Huber", "Kaiser", "Fuchs", "Peters", "Lang", "Scholz", "Möller", "Weiß", "Jung", "Hahn", "Schubert", "Vogel", "Friedrich", "Keller", "Günther", "Frank", "Berger", "Winkler", "Roth", "Beck", "Lorenz", "Baumann", "Franke", "Albrecht", "Schuster", "Simon", "Ludwig", "Böhm", "Winter", "Kraus", "Martin", "Schumacher", "Krämer", "Vogt", "Stein", "Jäger", "Otto", "Sommer", "Groß", "Seidel", "Heinrich", "Brandt", "Haas", "Schreiber", "Graf", "Schulte", "Dietrich", "Ziegler", "Kuhn", "Kühn", "Pohl", "Engel", "Horn", "Busch", "Bergmann", "Thomas", "Voigt", "Sauer", "Arnold", "Wolff", "Pfeiffer", "Seifert", "Funk", "Kraft", "Beyer", "Kern", "Witt", "Peter", "Barth", "Lorenz", "Schwartz", "Maurer", "Riedel", "Smith", "Johnson", "Williams", "Jones", "Brown", "Davis", "Miller", "Wilson", "Moore", "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson", "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "Hernandez", "King", "Wright", "Lopez", "Hill", "Scott", "Green", "Adams", "Baker", "Gonzalez", "Nelson", "Carter", "Mitchell", "Perez", "Roberts", "Turner", "Phillips", "Campbell", "Parker", "Evans", "Edwards", "Collins", "Stewart", "Sanchez", "Morris", "Rogers", "Reed", "Cook", "Morgan", "Bell", "Murphy", "Bailey", "Rivera", "Cooper", "Richardson", "Cox", "Howard", "Ward", "Torres", "Peterson", "Gray", "Ramirez", "James", "Watson", "Brooks", "Kelly", "Sanders", "Price", "Bennett", "Wood", "Barnes", "Ross", "Henderson", "Coleman", "Jenkins", "Perry", "Powell", "Long", "Patterson", "Hughes", "Flores", "Washington", "Butler", "Simmons", "Foster", "Gonzales", "Bryant", "Alexander", "Russell", "Griffin", "Diaz", "Hayes"];
        public static string[] Cities = [ "Wien", "Berlin", "Paris", "London", "Madrid", "Rom", "Prag", "Budapest", "Warschau", "Stockholm", "Oslo", "Helsinki", "Kopenhagen", "Amsterdam", "Brüssel", "Lissabon", "Dublin", "Athen", "Bukarest", "Sofia", "Nicosia", "Tallinn", "Riga", "Vilnius", "Valletta", "Luxemburg", "Bratislava", "Ljubljana", "Nikosia", "Zagreb" ];
        public static string[] StreetNames = [ "Hauptstraße", "Hochstraße", "Breitstraße", "Wallstraße", "Flottenstraße", "Downingstraße", "Bäckerstraße", "Abteistraße", "Sonnenuntergangsboulevard", "Hollywoodboulevard", "Rodeodrive", "Weinberg", "Weinberggasse" ];
        public static string[] Countries = [ "Österreich", "Deutschland", "Frankreich", "Großbritannien", "Spanien", "Italien", "Tschechien", "Ungarn", "Polen", "Schweden", "Norwegen", "Finnland", "Dänemark", "Niederlande", "Belgien", "Portugal", "Irland", "Griechenland", "Rumänien", "Bulgarien", "Zypern", "Estland", "Lettland", "Litauen", "Malta", "Luxemburg", "Slowakei", "Slowenien", "Zypern", "Kroatien" ];
    }
}
