# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Nuget

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+" 

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies 
      run: dotnet restore
      
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
      
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build

    - name: Pack
      run: dotnet pack Infrastructure.Core --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Pack
      run: dotnet pack Infrastructure.Core.PostgreSQL --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Pack
      run: dotnet pack Infrastructure.Core.SqlServer --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Pack
      run: dotnet pack Infrastructure.Core.Web --configuration Release /p:Version=${VERSION} --no-build --output .

    - name: Push
      run: dotnet nuget push SoftwaredeveloperDotAt.Infrastructure.Core.${VERSION}.nupkg --api-key ${NUGET_TOKEN} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

    - name: Push
      run: dotnet nuget push SoftwaredeveloperDotAt.Infrastructure.Core.PostgreSQL.${VERSION}.nupkg --api-key ${NUGET_TOKEN} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        
    - name: Push
      run: dotnet nuget push SoftwaredeveloperDotAt.Infrastructure.Core.SqlServer.${VERSION}.nupkg --api-key ${NUGET_TOKEN} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        
    - name: Push
      run: dotnet nuget push SoftwaredeveloperDotAt.Infrastructure.Core.Web.${VERSION}.nupkg --api-key ${NUGET_TOKEN} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

      
